<%@page import="java.sql.PreparedStatement"%>
<%@page import="java.sql.DriverManager"%>
<%@page import="java.sql.Connection"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Deposit</title>
</head>
<body>
	<%
	String acct_no = request.getParameter("acct_no");
	String cname = request.getParameter("cname");
	String caddress = request.getParameter("caddress");
	String mobile = request.getParameter("mobile");
	String email = request.getParameter("email");

	try {
		Class.forName("com.mysql.cj.jdbc.Driver");
		Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ATM", "root", "root");

	
		String s1 = "INSERT into banking values (?,?,?,?,?) ";
		//	PreparedStatement st = con.prepareStatement("INSERT into banking (acct_no, cname, caddress, mobile, email" + "(?,?,?,?,?)",
		//	Statement.RETURN_GENERATED_KEYS);
		//	ResultSet tableKeys = st.getGeneratedKeys();
		//	st.executeUpdate();
		//	tableKeys.next();
		//	int autoGeneratedID = tableKeys.getInt(1);

		PreparedStatement st = con.prepareStatement(s1);

		st.setString(1, acct_no);
		st.setString(2, cname);
		st.setString(3, caddress);
		st.setString(4, mobile);
		st.setString(5, email);

		st.executeUpdate();

	} catch (Exception e) {
		e.printStackTrace();
	}
	%>
</body>
</html>